services:
  xampp:
    image: tomsik68/xampp
    container_name: xampp_container
    ports:
      - "8080:80"   # Accès Apache via http://localhost:8080
      - "3306:3306" # Accès MySQL (si besoin d'une connexion externe)
    volumes:
      - .:/opt/lampp/htdocs  # Monte tout le projet CMS dans /opt/lampp/htdocs
    restart: always